# Generated by Django 6.0.3 on 2026-04-06 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('history', 'История'), ('literature', 'Литература'), ('cs', 'Информатика'), ('languages', 'Языки'), ('philosophy', 'Философия'), ('other', 'Другое')], default='other', max_length=20)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
