# Generated by Django 6.0.3 on 2026-04-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('web', 'Веб-разработка'), ('mobile', 'Мобильная'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('writing', 'Копирайтинг'), ('video', 'Видео'), ('data', 'Данные/ML'), ('devops', 'DevOps'), ('other', 'Другое')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='open', max_length=20)),
                ('budget_type', models.CharField(choices=[('fixed', 'Фиксированный'), ('hourly', 'Почасовой')], default='fixed', max_length=10)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'freelancer')},
            },
        ),
    ]
