# Generated by Django 6.0.3 on 2026-04-06 20:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('tablet', 'Таблетки'), ('capsule', 'Капсулы'), ('syrup', 'Сироп'), ('injection', 'Инъекция'), ('drops', 'Капли'), ('spray', 'Спрей'), ('patch', 'Пластырь'), ('other', 'Другое')], default='tablet', max_length=20)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(choices=[('once', '1 раз в день'), ('twice', '2 раза в день'), ('three', '3 раза в день'), ('four', '4 раза в день'), ('weekly', '1 раз в неделю'), ('as_needed', 'По необходимости')], default='once', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('morning', 'Утро (~08:00)'), ('afternoon', 'День (~13:00)'), ('evening', 'Вечер (~19:00)'), ('night', 'Ночь (~22:00)')], max_length=20)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='items.item')),
            ],
            options={
                'ordering': ['time_of_day'],
                'unique_together': {('medication', 'time_of_day')},
            },
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('taken', 'Принято'), ('missed', 'Пропущено'), ('skipped', 'Пропущено намеренно')], default='taken', max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='items.item')),
            ],
            options={
                'ordering': ['-date', 'time_of_day'],
                'unique_together': {('user', 'medication', 'time_of_day', 'date')},
            },
        ),
    ]
