# Generated by Django 6.0.3 on 2026-04-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('style', models.CharField(choices=[('vinyasa', 'Виньяса'), ('hatha', 'Хатха'), ('yin', 'Инь'), ('power', 'Силовая'), ('restorative', 'Восстановительная'), ('ashtanga', 'Аштанга'), ('kundalini', 'Кундалини'), ('other', 'Другое')], default='hatha', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('focus', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=200)),
                ('sanskrit_name', models.CharField(blank=True, default='', max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('instructions', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='items.item')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
