# Generated by Django 6.0.3 on 2026-04-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('room', 'Комната'), ('commercial', 'Коммерция'), ('land', 'Участок')], default='apartment', max_length=20)),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('reserved', 'Забронировано'), ('sold', 'Продано'), ('rented', 'Сдано')], default='active', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
