# Generated by Django 6.0.3 on 2026-04-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('specialization', models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('dentist', 'Стоматолог'), ('cardiologist', 'Кардиолог'), ('neurologist', 'Невролог'), ('ophthalmologist', 'Офтальмолог'), ('dermatologist', 'Дерматолог'), ('pediatrician', 'Педиатр'), ('ent', 'ЛОР'), ('orthopedist', 'Ортопед')], default='therapist', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Принимает'), ('busy', 'Занят'), ('day_off', 'Выходной'), ('vacation', 'Отпуск')], default='available', max_length=20)),
                ('cabinet', models.CharField(blank=True, default='', max_length=20)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('reception_time', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('status', models.CharField(choices=[('booked', 'Забронировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='booked', max_length=20)),
                ('complaint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='items.item')),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('doctor', 'date', 'time_slot')},
            },
        ),
    ]
