# Generated by Django 6.0.3 on 2026-04-06 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('freelance', 'Фриланс'), ('investment', 'Инвестиции'), ('other_income', 'Прочий доход'), ('food', 'Еда'), ('transport', 'Транспорт'), ('housing', 'Жильё'), ('utilities', 'Коммунальные'), ('health', 'Здоровье'), ('education', 'Образование'), ('entertainment', 'Развлечения'), ('clothing', 'Одежда'), ('savings', 'Накопления'), ('other_expense', 'Прочий расход')], default='other_expense', max_length=20)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('freelance', 'Фриланс'), ('investment', 'Инвестиции'), ('other_income', 'Прочий доход'), ('food', 'Еда'), ('transport', 'Транспорт'), ('housing', 'Жильё'), ('utilities', 'Коммунальные'), ('health', 'Здоровье'), ('education', 'Образование'), ('entertainment', 'Развлечения'), ('clothing', 'Одежда'), ('savings', 'Накопления'), ('other_expense', 'Прочий расход')], max_length=20)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('owner', 'category', 'month')},
            },
        ),
    ]
